# Generated by Django 5.2.5 on 2025-09-26 11:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=7,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("payment", "Payment"), ("fine", "Fine")],
                        default="payment",
                        max_length=7,
                    ),
                ),
                ("session_url", models.URLField(blank=True, max_length=500, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "money_to_pay",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=7
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "borrowing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="borrowings.borrowing",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("money_to_pay__gt", 0)),
                        name="positive_money_to_pay",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("session_id__isnull", False)),
                        fields=("session_id",),
                        name="unique_session_id",
                    ),
                ],
            },
        ),
    ]
