# Generated by Django 5.2.5 on 2025-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
