# Generated by Django 5.2.5 on 2025-08-25 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                (
                    "cover",
                    models.CharField(
                        choices=[("hard", "Hard"), ("soft", "Soft")],
                        default="hard",
                        max_length=20,
                    ),
                ),
                ("inventory", models.PositiveSmallIntegerField(default=0)),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(999.99),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
