# Generated by Django 5.2.5 on 2025-09-26 09:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                (
                    "cover",
                    models.CharField(
                        choices=[("hard", "Hard"), ("soft", "Soft")],
                        default="hard",
                        max_length=4,
                    ),
                ),
                ("inventory", models.PositiveIntegerField(default=0)),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["title", "author"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("inventory__gte", 0)),
                        name="positive_inventory",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("daily_fee__gt", 0)), name="positive_fee"
                    ),
                ],
            },
        ),
    ]
