# Generated by Django 5.2.5 on 2025-08-29 19:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["title", "author"],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("hard", "Hard"), ("soft", "Soft")],
                default="hard",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Daily borrowing fee in USD",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(
                help_text="Number of copies available in the library",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.CheckConstraint(
                condition=models.Q(("inventory__gte", 0)), name="inventory_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.CheckConstraint(
                condition=models.Q(("daily_fee__gt", 0)), name="daily_fee_positive"
            ),
        ),
    ]
