# Generated by Django 5.2.5 on 2025-09-04 14:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_options_alter_book_cover_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title", "author"]},
        ),
        migrations.RemoveConstraint(
            model_name="book",
            name="inventory_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="book",
            name="daily_fee_positive",
        ),
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.CheckConstraint(
                condition=models.Q(("inventory__gte", 0)), name="positive_inventory"
            ),
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.CheckConstraint(
                condition=models.Q(("daily_fee__gt", 0)), name="positive_fee"
            ),
        ),
    ]
