# Generated by Django 5.2.5 on 2025-09-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="borrow_date_not_future",
        ),
    ]
