# Generated by Django 5.2.5 on 2025-09-18 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_remove_borrowing_borrow_date_not_future"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 9, 18, 14, 58, 18, 429232, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
