# Generated by Django 5.2.5 on 2025-09-18 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0003_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 9, 18, 19, 47, 20, 444476, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
