# Generated by Django 5.2.5 on 2025-09-18 19:59

import borrowings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0005_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(default=borrowings.models.kyiv_today),
        ),
    ]
